//ブックマークレット生成機
javascript:(function(){
  trgr();
  function trgr(){
  	d = window.open().document;
	d.write('<!DOCTYPE html>');
	d.write('<html lang="ja">');
	d.write('<head>');
	d.write('<meta charset="utf-8">');
	d.write('<style type="text/css">');
	d.write('* {font-family:"メイリオ",Meiryo,sans-serif;}');
	d.write('input,textarea,label{font-size: 95%;}');
	d.write('button#bkm_create_btn {font-size:110%;}');
	d.write('dd {margin-left: 0;}');
	d.write('#bkm {border-collapse: collapse;width: 600px;}');
	d.write('#bkm th {background: #eee;border:3px solid #fff;padding: 5px;}');
	d.write('#bkm td {background: #FFFFE0;border:3px solid #fff;padding: 5px;}');
	d.write('#bkm_comments,#bkm_srccode {width: 430px;}');
	d.write('#bkm td.btnarea {text-align: center;background: #eee;}');
	d.write('#bkm td.codeare {background: #eee;}');
	d.write('#bkm_code {width: 600px; height: 10em;}');
	d.write('</style>');
	d.write('</head>');
	d.write('<body>');
	d.write('<script type="text/javascript">');
	d.write('function bkm_create(){');
	d.write('var bkm_body = "javascript:(function(){";');
	d.write('var bkm_results = document.getElementsByName("bkm_result");');
	d.write('var bkm_result_val = "";');
	d.write('for(var i=0; i<bkm_results.length; i++){');
	d.write('if(bkm_results[i].checked==true){');
	d.write('bkm_result_val = bkm_results[i].value;');
	d.write('break;');
	d.write('}');
	d.write('}');
	d.write('var bkm_comments_status = document.getElementsByName("bkm_comment_status");');
	d.write('var bkm_comment_status_val = "";');
	d.write('for(var i=0; i<bkm_comments_status.length; i++){');
	d.write('if(bkm_comments_status.item(i).checked==true){');
	d.write('bkm_comment_status_val = bkm_comments_status[i].value;');
	d.write('break;');
	d.write('}');
	d.write('}');
	d.write('var bkm_srccodes_status = document.getElementsByName("bkm_srccode_status");');
	d.write('var bkm_srccode_status_val = "";');
	d.write('for(var i=0; i<bkm_srccodes_status.length; i++){');
	d.write('if(bkm_srccodes_status[i].checked==true){');
	d.write('bkm_srccode_status_val = bkm_srccodes_status[i].value;');
	d.write('break;');
	d.write('}');
	d.write('}');
	d.write('var bkm_autosaves = document.getElementsByName("bkm_autosave");');
	d.write('var bkm_autosave_val = "";');
	d.write('for(var i=0; i<bkm_autosaves.length; i++){');
	d.write('if(bkm_autosaves[i].checked==true){');
	d.write('bkm_autosave_val = bkm_autosaves[i].value;');
	d.write('break;');
	d.write('}');
	d.write('}');
	d.write('switch(bkm_result_val){');
	d.write('case "0":');
	d.write('bkm_body += \'var form=document.forms["diag_form"];for(var i=0;i<form.elements.length;i++){var obj=form.elements[i].value;if(obj=="PASS"){form.elements[i].click();break;}}\';');
	d.write('break;');
	d.write('case "1":');
	d.write('bkm_body += \'var form=document.forms["diag_form"];for(var i=0;i<form.elements.length;i++){var obj=form.elements[i].value;if(obj=="PASS2"){form.elements[i].click();break;}}\';');
	d.write('break;');
	d.write('case "2":');
	d.write('bkm_body += \'var form=document.forms["diag_form"];for(var i=0;i<form.elements.length;i++){var obj=form.elements[i].value;if(obj=="FAIL"){form.elements[i].click();break;}}\';');
	d.write('break;');
	d.write('case "3":');
	d.write('bkm_body += \'var form=document.forms["diag_form"];for(var i=0;i<form.elements.length;i++){var obj=form.elements[i].value;if(obj=="FAIL2"){form.elements[i].click();break;}}\';');
	d.write('break;');
	d.write('default:');
	d.write('bkm_body += \'var form=document.forms["diag_form"];for(var i=0;i<form.elements.length;i++){var obj=form.elements[i].value;if(obj=="NA"){form.elements[i].click();break;}}\';');
	d.write('break;');
	d.write('}');
	d.write('if(bkm_comment_status_val=="0"){');
	d.write('var val1 = document.getElementById("bkm_comments").value;');
	d.write('bkm_body += \'document.getElementById("comments").value="\';');
	d.write('bkm_body += val1 + \'";\';');
	d.write('}');
	d.write('if(bkm_srccode_status_val=="0"){');
	d.write('var val2 = document.getElementById("bkm_srccode").value;');
	d.write('bkm_body += \'document.getElementById("srccode").value="\';');
	d.write('bkm_body += val2 + \'";\';');
	d.write('}');
	d.write('if(bkm_autosave_val=="0"){');
	d.write('bkm_body += \'for(var i=0;i<form.elements.length;i++){var obj=form.elements[i].type;if(obj=="submit"){form.elements[i].click();}}\';');
	d.write('}');
	d.write('bkm_body += \'})();\';');
	d.write('document.getElementById("bkm_code").value = bkm_body;');
	d.write('}');
	d.write('function clear_this_text(obj){');
	d.write('document.getElementById(obj).value = "";');
	d.write('}');
	d.write('</script>');
	d.write('<h1>Bookmarkletter</h1>');
	d.write('<table id="bkm">');
	d.write('<tr>');
	d.write('<th><label for="bkm_result">判定結果</label></th>');
	d.write('<td>');
	d.write('<label><input type="radio" name="bkm_result" value="0">適合</label>');
	d.write('<label><input type="radio" name="bkm_result" value="1">適合(注記)</label>');
	d.write('<label><input type="radio" name="bkm_result" value="2">不適合</label>');
	d.write('<label><input type="radio" name="bkm_result" value="3">不適合(要判定)</label>');
	d.write('<label><input type="radio" name="bkm_result" value="4">非適用 </label>');
	d.write('</td>');
	d.write('</tr>');
	d.write('<tr>');
	d.write('<th><label for="bkm_comments">判定コメント</label></th>');
	d.write('<td>');
	d.write('<dl>');
	d.write('<dt>');
	d.write('<label><input type="radio" name="bkm_comment_status" value="0">はい</label>');
	d.write('<label><input type="radio" name="bkm_comment_status" value="1">いいえ</label>');
	d.write('</dt>');
	d.write('<dd><textarea id="bkm_comments"></textarea><br>');
	d.write('<button onclick="clear_this_text(\'bkm_comments\')">Clear</button>');
	d.write('</dd>');
	d.write('</dl>');
	d.write('</td>');
	d.write('</tr>');
	d.write('<tr>');
	d.write('<th><label for="bkm_srccode">修正ソースコード</label></th>');
	d.write('<td>');
	d.write('<dl>');
	d.write('<dt>');
	d.write('<label><input type="radio" name="bkm_srccode_status" value="0">はい</label>');
	d.write('<label><input type="radio" name="bkm_srccode_status" value="1">いいえ</label>');
	d.write('</dt>');
	d.write('<dd><textarea id="bkm_srccode"></textarea><br>');
	d.write('<button onclick="clear_this_text(\'bkm_srccode\')">Clear</button>');
	d.write('</dd>');
	d.write('</dl>');
	d.write('</td>');
	d.write('</tr>');
	d.write('<tr>');
	d.write('<th>自動登録</th>');
	d.write('<td>');
	d.write('<label><input type="radio" name="bkm_autosave" value="0">はい</label>');
	d.write('<label><input type="radio" name="bkm_autosave" value="1">いいえ</label>');
	d.write('</td>');
	d.write('</tr>');
	d.write('<tr>');
	d.write('<td colspan="2" class="btnarea">');
	d.write('<button id="bkm_create_btn" onclick="bkm_create()">Create</button>');
	d.write('</td>');
	d.write('</tr>');
	d.write('<tr>');
	d.write('<td colspan="2" class="codearea"><textarea id="bkm_code"></textarea><br>');
	d.write('<button onclick="clear_this_text(\'bkm_code\')">Clear</button>');
	d.write('</td>');
	d.write('</tr>');
	d.write('</table>');
	d.write('</body>');
	d.write('</html>');
  }
})();
