javascript:(function() {
	function trgr() {
			var wrap_id = 'BSurfin_diag';
			if(document.getElementById(wrap_id)) {
				return;
			}
			var wrap = document.createElement('div');
			var btnfunc = 'erase_diag(this); erase_script(); erase_style();';
			wrap.id = wrap_id;
			var my_html = '<div style="padding:3px;background:#eee;height:19px;">';
			my_html += '<span style="float:left;""<strong>検査対象ページ連続参照</strong></span>';
			my_html += '<a style="float:right;" onclick="' + btnfunc + '">閉じる</a></div>';
			my_html += '<label>参照URL</label>';
			my_html += '<select id="pup_urls" onchange="do_load()"></select>';
			my_html += '<button onclick="do_prev()">前へ</button>';
			my_html += '<button onclick="do_next()">次へ</button>';
			my_html += '<button onclick="do_load()">再読込</button>';
			my_html += '<button onclick="do_browse_tab()">タブで開く</button><br>';
			my_html += '<iframe id="pup_display" src=""></iframe>';
			wrap.innerHTML = my_html;
			document.getElementsByTagName('body')[0].appendChild(wrap);
			var tbl = document.getElementsByTagName("table").item(2);
			var tr = tbl.rows;
			for(var i=0; i<tr.length; i++) {
				if(i < 2) continue;
				var row = tr.item(i);
				var pgid = row.cells.item(0).innerHTML;
				var pgurl = row.cells.item(1).innerHTML;
				var elm = document.createElement("option");
				elm.setAttribute("value", pgid);
				elm.textContent = "[" + pgid + "]" + pgurl;
				document.getElementById("pup_urls").appendChild(elm);
			}
			var target_src = document.getElementById("pup_urls");
			var target_text_all = target_src.options[target_src.selectedIndex].text;
			var pat = new RegExp(/(\[.+?\])(.+)/);
			var arr = target_text_all.match(pat);
			var target_text = arr[2].toString();
			document.getElementById("pup_display").setAttribute("src", target_text);
			if(document.getElementById("hdjs") == null) {
				var hdjs = document.createElement('script');
				hdjs.id = 'hdjs';
				hdjs.type = 'text/javascript';
				var hdjs_str = '';
				hdjs_str += 'var e = document.getElementById("BSurfin_diag");';
				hdjs_str += 'var flag;';
				hdjs_str += 'var clickOffsetTop;';
				hdjs_str += 'var clickOffsetLeft;';
				hdjs_str += 'e.onmousedown = function(evt) {';
				hdjs_str += 'flag = "on";';
				hdjs_str += 'evt = (evt) || window.event;';
				hdjs_str += 'clickOffsetTop = evt.clientY - e.offsetTop;';
				hdjs_str += 'clickOffsetLeft = evt.clientX - e.offsetLeft;';
				hdjs_str += 'if(!document.all) {';
				hdjs_str += 'window.getSelection().removeAllRanges();';
				hdjs_str += '}';
				hdjs_str += '};';
				hdjs_str += 'document.onmouseup = function() {';
				hdjs_str += 'flag = "off";';
				hdjs_str += '};';
				hdjs_str += 'document.onmousemove = function(evt) {';
				hdjs_str += 'evt = (evt) || window.event;';
				hdjs_str += 'if(flag == "on") {';
				hdjs_str += 'e.style.top = evt.clientY - clickOffsetTop + "px";';
				hdjs_str += 'e.style.left = evt.clientX - clickOffsetLeft + "px";';
				hdjs_str += '}';
				hdjs_str += '};';
				hdjs.textContent = hdjs_str;
				document.getElementsByTagName("head").item(0).appendChild(hdjs);
			}
			if(document.getElementById("mycss") == null) {
				var mycss = document.createElement('style');
				mycss.id = 'mycss';
				mycss.type = 'text/css';
				var mycss_str = '';
				mycss_str += '#BSurfin_diag {';
				mycss_str += 'font-family:"メイリオ",sans-serif;font-size:90%;';
				mycss_str += 'padding:5px;position:absolute;top:0;left:0;background:#fff;border:solid #ccc 1px;';
				mycss_str += 'z-index:2999;width:1024px;height:570px;';
				mycss_str += '}';
				mycss_str += '#pup_urls { width: 500px; }';
				mycss_str += '#pup_display { width: 1024px; height: 520px;}';
				mycss.textContent = mycss_str;
				document.getElementsByTagName("head").item(0).appendChild(mycss);
			}
			if(document.getElementById("myjs") == null) {
				var myjs = document.createElement('script');
				myjs.type = 'text/javascript';
				myjs.id = 'myjs';
				var myjs_str = '';
				myjs_str += 'function do_browse_tab() {';
				myjs_str += 'var target_src = document.getElementById("pup_urls");';
				myjs_str += 'var target_text_all = target_src.options[target_src.selectedIndex].text;';
				myjs_str += 'var pat = new RegExp(/(\\[.+?\\])(.+)/);';
				myjs_str += 'var arr = target_text_all.match(pat);';
				myjs_str += 'var target_text = arr[2].toString();';
				myjs_str += 'window.open(target_text, "_blank");';
				myjs_str += '}';
				myjs_str += 'function do_load() {';
				myjs_str += 'var target_src = document.getElementById("pup_urls");';
				myjs_str += 'var target_text_all = target_src.options[target_src.selectedIndex].text;';
				myjs_str += 'var pat = new RegExp(/(\\[.+?\\])(.+)/);';
				myjs_str += 'var arr = target_text_all.match(pat);';
				myjs_str += 'var target_text = arr[2].toString();';
				myjs_str += 'var target_frame = document.getElementById("pup_display");';
				myjs_str += 'target_frame.setAttribute("src", target_text);';
				myjs_str += '}';
				myjs_str += 'function do_next() {';
				myjs_str += 'var src = document.getElementById("pup_urls");';
				myjs_str += 'var max = src.length;';
				myjs_str += 'var idx = src.selectedIndex;';
				myjs_str += 'idx++;';
				myjs_str += 'if(idx >= max) {';
				myjs_str += 'alert("これ以上進めません");';
				myjs_str += '} else {';
				myjs_str += 'src.selectedIndex = idx;';
				myjs_str += 'do_load();';
				myjs_str += '}';
				myjs_str += '}';
				myjs_str += 'function do_prev() {';
				myjs_str += 'var src = document.getElementById("pup_urls");';
				myjs_str += 'var min = 0;';
				myjs_str += 'var idx = src.selectedIndex;';
				myjs_str += 'idx--;';
				myjs_str += 'if(idx < min) {';
				myjs_str += 'alert("これ以上戻れません");';
				myjs_str += '} else {';
				myjs_str += 'src.selectedIndex = idx;';
				myjs_str += 'do_load();';
				myjs_str += '}';
				myjs_str += '}';
				myjs_str += 'function erase_diag(obj) {obj.parentNode.parentNode.parentNode.removeChild(obj.parentNode.parentNode);}';
				myjs_str += 'function erase_script() {';
				myjs_str += 'var obj = document.getElementById("myjs");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += 'var obj = document.getElementById("hdjs");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += '}';
				myjs_str += 'function erase_style() {';
				myjs_str += 'var obj = document.getElementById("mycss");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += '}';
				myjs.textContent = myjs_str;
				document.body.appendChild(myjs);
			}
            window.scrollTo(0, 0);
	}
	trgr();
})();