javascript:(function() {
	function trgr() {
			var wrap_id = 'Replacer_diag';
			if(document.getElementById(wrap_id)) {
				return;
			}
			var wrap = document.createElement('div');
			var btnfunc = 'erase_diag(this); erase_script(); erase_style();';
			wrap.id = wrap_id;
			var my_html = '<div style="padding:3px;background:#eee;height:19px;">';
			my_html += '<span style="float:left;""<strong>CCAコメントエディタ</strong></span>';
			my_html += '<a style="float:right;" onclick="' + btnfunc + '">閉じる</a></div>';
			my_html += '<label><input type="radio" name="cd" id="cd18" value="G18" checked="checked">G18</label>';
			my_html += '<label><input type="radio" name="cd" id="cd145" value="G145">G145</label>';
			my_html += '<select id="snippet"></select>';
			my_html += '<button onclick="this_text_insert(\'snippet\',\'tb\')">Insert</button>';
			my_html += '<br>';
			my_html += '<button onclick="clean()">Clean</button>';
			my_html += '<button onclick="br_insert(\'tb\')">Br</button>';
			my_html += '<button onclick="write_comment()">Cmt</button>';
			my_html += '<button onclick="delete_text()">Del</button>';
			my_html += '<button onclick="copy_bottom()">CpBottom</button>';
			my_html += '<button onclick="send_text()">SendCmt</button>';
			my_html += '<button onclick="delete_srccode()">DelSrc</button><br>';
			my_html += '<textarea id="tb"></textarea><br>';
			my_html += '<button onclick="copy_up()">CpUpper</button>';
			my_html += '<button onclick="delete_subtext()">Del</button>';
			my_html += '<textarea id="ta"></textarea>';
			wrap.innerHTML = my_html;
			document.getElementsByTagName('body')[0].appendChild(wrap);
			var keylist = "のバナー|のメニュー|のボタン|の文字|の文字画像|の見出し|「 」|（　）|【 】|上の|下の|左の|右の|上下左右";
			var keyarr = keylist.split("|");
			var target = document.getElementById("snippet");
			for(var i=0; i<keyarr.length; i++){
				var opt = document.createElement("option");
				opt.setAttribute("id", i);
				opt.textContent = keyarr[i].toString();
				target.appendChild(opt);
			}
			if(document.getElementById("hdjs") == null) {
				var hdjs = document.createElement('script');
				hdjs.id = 'hdjs';
				hdjs.type = 'text/javascript';
				var hdjs_str = '';
				hdjs_str += 'var e = document.getElementById("Replacer_diag");';
				hdjs_str += 'var flag;';
				hdjs_str += 'var clickOffsetTop;';
				hdjs_str += 'var clickOffsetLeft;';
				hdjs_str += 'e.onmousedown = function(evt) {';
				hdjs_str += 'flag = "on";';
				hdjs_str += 'evt = (evt) || window.event;';
				hdjs_str += 'clickOffsetTop = evt.clientY - e.offsetTop;';
				hdjs_str += 'clickOffsetLeft = evt.clientX - e.offsetLeft;';
				hdjs_str += 'if(!document.all) {';
				hdjs_str += 'window.getSelection().removeAllRanges();';
				hdjs_str += '}';
				hdjs_str += '};';
				hdjs_str += 'document.onmouseup = function() {';
				hdjs_str += 'flag = "off";';
				hdjs_str += '};';
				hdjs_str += 'document.onmousemove = function(evt) {';
				hdjs_str += 'evt = (evt) || window.event;';
				hdjs_str += 'if(flag == "on") {';
				hdjs_str += 'e.style.top = evt.clientY - clickOffsetTop + "px";';
				hdjs_str += 'e.style.left = evt.clientX - clickOffsetLeft + "px";';
				hdjs_str += '}';
				hdjs_str += '};';
				hdjs.textContent = hdjs_str;
				document.getElementsByTagName("head").item(0).appendChild(hdjs);
			}
			if(document.getElementById("mycss") == null) {
				var mycss = document.createElement('style');
				mycss.id = 'mycss';
				mycss.type = 'text/css';
				var mycss_str = '';
				mycss_str += '#Replacer_diag {';
				mycss_str += 'font-family:"メイリオ",sans-serif;font-size:90%;';
				mycss_str += 'padding:5px;position:absolute;top:0;left:0;background:#fff;border:solid #ccc 1px;';
				mycss_str += 'z-index:2999;width:390px;height:320px;';
				mycss_str += '}';
				mycss_str += '#Replacer_diag textarea {';
				mycss_str += 'font-family:"メイリオ",sans-serif;font-size:90%;width:380px;height:7em;';
				mycss_str += '}';
				mycss.textContent = mycss_str;
				document.getElementsByTagName("head").item(0).appendChild(mycss);
			}
			if(document.getElementById("myjs") == null) {
				var myjs = document.createElement('script');
				myjs.type = 'text/javascript';
				myjs.id = 'myjs';
				var myjs_str = '';
				myjs_str += 'function get_text(){';
				myjs_str += 'return document.getElementById("tb").value;';
				myjs_str += '}';
				myjs_str += 'function set_text(str){';
				myjs_str += 'document.getElementById("tb").value = str;';
				myjs_str += '}';
				myjs_str += 'function delete_text(){';
				myjs_str += 'document.getElementById("tb").value = "";';
				myjs_str += '}';
				myjs_str += 'function delete_subtext(){';
				myjs_str += 'document.getElementById("ta").value = "";';
				myjs_str += '}';
				myjs_str += 'function copy_bottom(){';
				myjs_str += 'var str = get_text();';
				myjs_str += 'document.getElementById("ta").value = str;';
				myjs_str += '}';
				myjs_str += 'function copy_up(){';
				myjs_str += 'var str = document.getElementById("ta").value;';
				myjs_str += 'set_text(str);';
				myjs_str += '}';
				myjs_str += 'function clean(){';
				myjs_str += 'var src = get_text();';
				myjs_str += 'src=src.replace(/\\n\\n/g, "\\n");';
				myjs_str += 'set_text(src);';
				myjs_str += '}';
				myjs_str += 'function write_comment(){';
				myjs_str += 'var src = get_text();';
				myjs_str += 'if(get_radio_val()=="G18"){';
				myjs_str += ' src = "以下のコンテンツがコントラスト比4.5:1以上を満たさない\\n" + src;';
				myjs_str += '} else {';
				myjs_str += 'src = "以下のコンテンツがコントラスト比3:1以上を満たさない\\n" + src;';
				myjs_str += '}';
				myjs_str += 'set_text(src);';
				myjs_str += '}';
				myjs_str += 'function get_radio_val(){';
				myjs_str += 'var ret = "";';
				myjs_str += 'var arr = document.getElementsByName("cd");';
				myjs_str += 'for(var i=0; i<arr.length; i++){';
				myjs_str += 'if(arr[i].checked){';
				myjs_str += 'ret = arr[i].value;';
				myjs_str += 'break;';
				myjs_str += '}';
				myjs_str += '}';
				myjs_str += 'return ret;';
				myjs_str += '}';
				myjs_str += 'function get_caret(target){';
				myjs_str += 'var ta = document.getElementById(target);';
				myjs_str += 'var start = ta.selectionStart;';
				myjs_str += 'return start;';
				myjs_str += '}';
				myjs_str += 'function text_insert(target, str){';
				myjs_str += 'var ta = document.getElementById(target);';
				myjs_str += 'var taval = ta.value;';
				myjs_str += 'var caret = get_caret(target);';
				myjs_str += 'var first2caret = taval.substring(0, caret);';
				myjs_str += 'var caret2end = taval.substring(caret, taval.length);';
				myjs_str += 'var rdmstr = first2caret + str + caret2end;';
				myjs_str += 'ta.value = rdmstr;';
				myjs_str += '}';
				myjs_str += 'function this_text_insert(src, target){';
				myjs_str += 'var sc = document.getElementById(src);';
				myjs_str += 'var text = sc.value;';
				myjs_str += 'text_insert(target, text);';
				myjs_str += '}';
				myjs_str += 'function br_insert(target){';
				myjs_str += 'text_insert(target, "\\n");';
				myjs_str += '}';
				myjs_str += 'function send_text() {';
				myjs_str += 'var src = document.getElementById("tb").value;';
				myjs_str += 'document.getElementById("comments").value = src;';
				myjs_str += '}';
				myjs_str += 'function delete_srccode() {';
				myjs_str += 'document.getElementById("srccode").value = "";';
				myjs_str += '}';
				myjs_str += 'function erase_diag(obj) {obj.parentNode.parentNode.parentNode.removeChild(obj.parentNode.parentNode);}';
				myjs_str += 'function erase_script() {';
				myjs_str += 'var obj = document.getElementById("myjs");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += 'var obj = document.getElementById("hdjs");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += '}';
				myjs_str += 'function erase_style() {';
				myjs_str += 'var obj = document.getElementById("mycss");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += '}';
				myjs.textContent = myjs_str;
				document.body.appendChild(myjs);
			}
            window.scrollTo(0, 0);
	}
	trgr();
})();