javascript:(function() {
	var args = "代替テキストが十分でない|段落の体裁を取っている箇所でp要素が使用されていない";
	function trgr(args) {
			var wrap_id = 'Editor_diag';
			if(document.getElementById(wrap_id)) {
				return;
			}
			var wrap = document.createElement('div');
			var btnfunc = 'erase_diag(this); erase_script(); erase_style();';
			wrap.id = wrap_id;
			var my_html = '<div style="padding:3px;background:#eee;height:19px;">';
			my_html += '<span style="float:left;""<strong>検査内容エディタ</strong></span>';
			my_html += '<a style="float:right;" onclick="' + btnfunc + '">閉じる</a></div>';
			my_html += '<label>【処理対象】</label><br>';
			my_html += '<label><input type="radio" name="cmd" id="cmd_comments" value="comments" checked="checked">判定コメント</label>';
			my_html += '<label><input type="radio" name="cmd" id="cmd_description" value="description">対象ソース</label>';
			my_html += '<label><input type="radio" name="cmd" id="cmd_srccode" value="srccode">修正ソース</label>';
			my_html += '<br>';
			my_html += '<label>【テキスト編集】</label><br>';
			my_html += '<button onclick="clean()">Clean</button>';
			my_html += '<button onclick="br_insert()">Br</button>';
			my_html += '<button onclick="delete_text()">Del</button>';
			my_html += '<br>';
			my_html += '<label>【コメント挿入】</label><br>';
			my_html += '<select id="snippet"></select>';
			my_html += '<button onclick="this_text_insert(\'snippet\')">挿入</button><br>';
			my_html += '<label>【テキスト置換】</label><br>';
			my_html += '<label>検索文字列</label><input type="text" id="my_search_text"><label>置換文字列</label><input type="text" id="my_replace_text">';
			my_html += '<button onclick="do_replace()">実行</button>';
			wrap.innerHTML = my_html;
			document.getElementsByTagName('body')[0].appendChild(wrap);
			var keyarr = args.split("|");
			var target = document.getElementById("snippet");
			for(var i=0; i<keyarr.length; i++){
				var opt = document.createElement("option");
				opt.setAttribute("id", i);
				opt.textContent = keyarr[i].toString();
				target.appendChild(opt);
			}
			if(document.getElementById("hdjs") == null) {
				var hdjs = document.createElement('script');
				hdjs.id = 'hdjs';
				hdjs.type = 'text/javascript';
				var hdjs_str = '';
				hdjs_str += 'var e = document.getElementById("Editor_diag");';
				hdjs_str += 'var flag;';
				hdjs_str += 'var clickOffsetTop;';
				hdjs_str += 'var clickOffsetLeft;';
				hdjs_str += 'e.onmousedown = function(evt) {';
				hdjs_str += 'flag = "on";';
				hdjs_str += 'evt = (evt) || window.event;';
				hdjs_str += 'clickOffsetTop = evt.clientY - e.offsetTop;';
				hdjs_str += 'clickOffsetLeft = evt.clientX - e.offsetLeft;';
				hdjs_str += 'if(!document.all) {';
				hdjs_str += 'window.getSelection().removeAllRanges();';
				hdjs_str += '}';
				hdjs_str += '};';
				hdjs_str += 'document.onmouseup = function() {';
				hdjs_str += 'flag = "off";';
				hdjs_str += '};';
				hdjs_str += 'document.onmousemove = function(evt) {';
				hdjs_str += 'evt = (evt) || window.event;';
				hdjs_str += 'if(flag == "on") {';
				hdjs_str += 'e.style.top = evt.clientY - clickOffsetTop + "px";';
				hdjs_str += 'e.style.left = evt.clientX - clickOffsetLeft + "px";';
				hdjs_str += '}';
				hdjs_str += '};';
				hdjs.textContent = hdjs_str;
				document.getElementsByTagName("head").item(0).appendChild(hdjs);
			}
			if(document.getElementById("mycss") == null) {
				var mycss = document.createElement('style');
				mycss.id = 'mycss';
				mycss.type = 'text/css';
				var mycss_str = '';
				mycss_str += '#Editor_diag {';
				mycss_str += 'font-family:"メイリオ",sans-serif;font-size:90%;';
				mycss_str += 'padding:5px;position:absolute;top:0;left:0;background:#fff;border:solid #ccc 1px;';
				mycss_str += 'z-index:2999;width:390px;height:190px;';
				mycss_str += '}';
				mycss_str += '#Editor_diag textarea {';
				mycss_str += 'font-family:"メイリオ",sans-serif;font-size:90%;width:380px;height:7em;';
				mycss_str += '}';
				mycss_str += '#Editor_diag label {font-size: 90%;}';
				mycss_str += '#my_search_text, #my_replace_text {width: 90px;}';
				mycss.textContent = mycss_str;
				document.getElementsByTagName("head").item(0).appendChild(mycss);
			}
			if(document.getElementById("myjs") == null) {
				var myjs = document.createElement('script');
				myjs.type = 'text/javascript';
				myjs.id = 'myjs';
				var myjs_str = '';
				myjs_str += 'function get_text(){';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'return document.getElementById(target).value;';
				myjs_str += '}';
				myjs_str += 'function set_text(str){';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'document.getElementById(target).value = str;';
				myjs_str += '}';
				myjs_str += 'function delete_text(){';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'document.getElementById(target).value = "";';
				myjs_str += '}';
				myjs_str += 'function clean(){';
				myjs_str += 'var src = get_text();';
				myjs_str += 'src=src.replace(/\\n\\n/g, "\\n");';
				myjs_str += 'set_text(src);';
				myjs_str += '}';
				myjs_str += 'function get_radio_val(){';
				myjs_str += 'var ret = "";';
				myjs_str += 'var arr = document.getElementsByName("cmd");';
				myjs_str += 'for(var i=0; i<arr.length; i++){';
				myjs_str += 'if(arr[i].checked){';
				myjs_str += 'ret = arr[i].value;';
				myjs_str += 'break;';
				myjs_str += '}';
				myjs_str += '}';
				myjs_str += 'return ret;';
				myjs_str += '}';
				myjs_str += 'function get_caret(){';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'var ta = document.getElementById(target);';
				myjs_str += 'var start = ta.selectionStart;';
				myjs_str += 'return start;';
				myjs_str += '}';
				myjs_str += 'function text_insert(str){';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'var ta = document.getElementById(target);';
				myjs_str += 'var taval = ta.value;';
				myjs_str += 'var caret = get_caret();';
				myjs_str += 'var first2caret = taval.substring(0, caret);';
				myjs_str += 'var caret2end = taval.substring(caret, taval.length);';
				myjs_str += 'var rdmstr = first2caret + str + caret2end;';
				myjs_str += 'ta.value = rdmstr;';
				myjs_str += '}';
				myjs_str += 'function this_text_insert(src){';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'var sc = document.getElementById(src);';
				myjs_str += 'var text = sc.value;';
				myjs_str += 'text_insert(text);';
				myjs_str += '}';
				myjs_str += 'function br_insert(){';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'text_insert("\\n");';
				myjs_str += '}';
				myjs_str += 'function do_replace() {';
				myjs_str += 'var target = get_radio_val();';
				myjs_str += 'var sh = document.getElementById("my_search_text").value;';
				myjs_str += 'var rp = document.getElementById("my_replace_text").value;';
				myjs_str += 'var src = document.getElementById(target).value;';
				myjs_str += 'var pt = new RegExp(sh, "mg");';
				myjs_str += 'src = src.replace(pt, rp);';
				myjs_str += 'document.getElementById(target).value = src;';
				myjs_str += '}';
				myjs_str += 'function erase_diag(obj) {obj.parentNode.parentNode.parentNode.removeChild(obj.parentNode.parentNode);}';
				myjs_str += 'function erase_script() {';
				myjs_str += 'var obj = document.getElementById("myjs");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += 'var obj = document.getElementById("hdjs");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += '}';
				myjs_str += 'function erase_style() {';
				myjs_str += 'var obj = document.getElementById("mycss");';
				myjs_str += 'obj.parentNode.removeChild(obj);';
				myjs_str += '}';
				myjs.textContent = myjs_str;
				document.body.appendChild(myjs);
			}
            window.scrollTo(0, 0);
	}
	trgr(args);
})();